### ISSUE TITLE
Error when input string greater than 31

### ISSUE THREAD

**Issue by proteomis** [DoHITB/CryptoCobol#1]
Hello, thank you for the program.
I have noticed that when the input string is greater or equal that 32, the program stops with an error "subscript out of range" in the "INPUT-TO-PADDING" paragraph. Under 32, there is no problem and the results are correct.
Is it something you can reproduce ?

Regards,

**Comment by DoHITB** [comment]
Hello:

Is this behaviour happening on SHA1HEX module? If so, that's an expected behaviour, as SHA1 works with a max size of 64 bytes (2 bytes per PIC, making 512 bits).

Please comfirm, if that's the scenario.
I will also check if there is something I can do to improve the scenario handling.

Thanks.

**Comment by proteomis** [comment]
This is SHA1HEX. I should have precise.
To be honest, I wasn't aware of length limitation for sha1. In the descrpition https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf  is is given a maximal message size of 2^64 (!). More than enough...
Regards

**Comment by DoHITB** [comment]
Hi:

Don't worry. Yes, it has 64 bytes size, so as input is expected on ASCII, thats 32 chars as each char is 2-byte wide.

I reviewed the code and the LINKAGE could lead to some missunderstanding. I will surely add some extra validations.

Thanks.

**Comment by DoHITB** [comment]
Added new validation on ```SHA1HEX```.
If ```length > 32```, it will move ```99``` as return (new variable on linkage); else it will move ```00``` and will continue with execution.

When calling ```SHA1HEX```, check for ```LS-ERROR-CODE```.
